### PR TITLE
Use dlopen() to load dynamic library at runtime

### PR DESCRIPTION
**Pull request by Rob1in**
**Goals**
This PR aims at loading libjpeg at runtime. 

dlopen() and symbol resolution are done in the init() function of the package and update a flag depending on success or not of those two.
Public functions of go-libjpeg are protected by this flag.
Making a best effort to find dynamic library if it was installed with brew on Linux or Darwin.

**Open questions**

- Path passed to dlopen() for Windows?
- which jpeglib.h?

**Follow-up PR**
Use native jpeg when dynamic library is not found.

### CODE REVIEW

**Comment by edaniels** [comment]
Swapping me with James who knows this better.

**Comment by Otterverse** [comment]
Before I get to reviewing the code itself, I'd like to understand the reasoning for this approach.

For one thing, I just finished several weeks of work in RDK explicitly REMOVING dynamic dependencies and linking things statically, including libjpeg. Runtime dlopen() makes that impossible, and puts us back to having to distribute/ship/install the shared library if we want customers to have an optimal experience, which is exactly what we're trying to avoid.

Secondly, is there a reason why you can't include a prebuilt static library directly in this go package instead? Several go packages are maintained that way, and the fact that they're using a c library becomes entirely transparent to the user... they just "go get pkg..." as usual, and it "just works." If you're not familar with this approach, a good example is the libopus code in the pionmedia library. https://github.com/pion/mediadevices/tree/master/pkg/codec/opus

You can see in the lib folder how there's a prebuilt static library (.a) for every supported platform. It feels like this would be a much better approach, as every user would get the same experience, and you wouldn't have dynamic version mismatches, and all those other headaches.

**Comment by Rob1in** [comment]
I went that path because the code sample in Go generated in the app wouldn't build simply with `go get go.viam.com/rdk/robot/client`without libjpeg. The idea was:

-  First, make sure that the code that we generate can be built without dependencies and returns an error if libjpeg can't be loaded at runtime. 

-  Then, implement a fallback to the native Go jpeg encoding library if libjpeg is not found. 

It seemed easier than having and maintaining static libraries for every platform but I understand the contradiction with the removal of dynamic dependencies. I am looking at the approach that you mentioned!

**Comment by Otterverse** [comment]
> I went that path because the code sample in Go generated in the app wouldn't build simply with `go get go.viam.com/rdk/robot/client`without libjpeg. The idea was:
> 
> * First, make sure that the code that we generate can be built without dependencies and returns an error if libjpeg can't be loaded at runtime.
> * Then, implement a fallback to the native Go jpeg encoding library if libjpeg is not found.
> 
> It seemed easier than having and maintaining static libraries for every platform but I understand the contradiction with the removal of dynamic dependencies. I am looking at the approach that you mentioned!

To be clear, it's not a bad idea in general, and would be flexible for a lot of normal use cases, but as far as I understand, it would make it impossible to statically link libjpeg, which is the path we're going down with RDK.

The other approach, of directly including static libraries, is (from the perspective of outside users) "the best" I think, but it definitely comes with some pain in building/maintaining those static libraries. Though, with how little libjpeg changes, you could probably build once by hand for each platform and call it done. Only if/when _this_ code needed/wanted a new function or feature would a rebuild be needed.

**Pull request closed without merging**
